[phases.setup]
nixpkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci --omit=dev --ignore-scripts --no-audit --no-fund']
phaseType = 'start'

[start]
cmd = 'node backend/src/server.js'
targetPort = 3000